# This rule is not used by the project llama-shepherd itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over llm.example.com.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: llama-shepherd
    app.kubernetes.io/managed-by: kustomize
  name: llminferencejob-admin-role
rules:
- apiGroups:
  - llm.example.com
  resources:
  - llminferencejobs
  verbs:
  - '*'
- apiGroups:
  - llm.example.com
  resources:
  - llminferencejobs/status
  verbs:
  - get
