---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.19.0
  name: kvcachepools.llm.example.com
spec:
  group: llm.example.com
  names:
    kind: KVCachePool
    listKind: KVCachePoolList
    plural: kvcachepools
    singular: kvcachepool
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: KVCachePool is the Schema for the kvcachepools API
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: spec defines the desired state of KVCachePool
            properties:
              replicas:
                default: 1
                description: |-
                  Replicas is the desired number of cache nodes.
                  If omitted, defaults to 1.
                format: int32
                type: integer
              strategy:
                default: lru
                description: |-
                  Strategy is the cache strategy, e.g. "lru", "lfu", "rr".
                  Right now it's just metadata; later it will drive eviction/placement.
                type: string
              totalMemoryGB:
                description: TotalMemoryGB is the total memory (across all replicas)
                  intended for KV cache.
                format: int32
                type: integer
            required:
            - totalMemoryGB
            type: object
          status:
            description: status defines the observed state of KVCachePool
            properties:
              readyReplicas:
                description: ReadyReplicas is how many cache nodes are currently ready.
                format: int32
                type: integer
            type: object
        required:
        - spec
        type: object
    served: true
    storage: true
    subresources:
      status: {}
